from flask import Flask, render_template, request, send_file
import joblib
import numpy as np
import pandas as pd
from fpdf import FPDF
import io

app = Flask(__name__)

# Load Model and Feature Names
model = joblib.load('model.pkl')
feature_names = joblib.load('features.pkl')
last_prediction = {}

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    global last_prediction
    user_input = request.form.to_dict()
    
    # Helper to handle empty strings
    def get_val(key):
        val = user_input.get(key, '0')
        return float(val) if val and val.strip() != '' else 0.0

    # --- STEP 1: BALANCED MANUAL SCORING (For Logic Control) ---
    manual_score = 0
    
    # Major Risk factors (Forces High Risk)
    if get_val('Dx') == 1: manual_score += 45
    if get_val('Smokes (years)') > 10: manual_score += 30
    
    # Moderate Risk factors (Forces Orange/Moderate Risk)
    if 1 <= get_val('Num of pregnancies') <= 3: manual_score += 15
    if 1 <= get_val('Hormonal Contraceptives (years)') <= 5: manual_score += 15
    if 1 <= get_val('IUD (years)') <= 3: manual_score += 10

    # --- STEP 2: GET AI MODEL SCORE ---
    final_features = []
    for col in feature_names:
        final_features.append(get_val(col))
    
    probs = model.predict_proba([final_features])
    ai_score = probs[0][1] * 100

    # --- STEP 3: HYBRID CALCULATION (Weighting 30% AI + 70% Logic) ---
    total_risk = min(round((ai_score * 0.3) + (manual_score * 0.7), 2), 99.0)

    # --- STEP 4: 3-LEVEL CATEGORIZATION ---
    if total_risk >= 40.0:
        result, res_color = "High Risk Identified - Clinical Consultation Recommended", "red"
    elif 15.0 <= total_risk < 40.0:
        result, res_color = "Moderate Risk - Follow-up Screening Advised", "orange"
    else:
        result, res_color = "Low Risk - Routine Monitoring", "green"
        # If no risk factors are provided, force the score to look low
        if manual_score == 0: total_risk = min(total_risk, 10.0)

    last_prediction = {
        'result': result, 
        'score': total_risk, 
        'inputs': user_input
    }
    
    return render_template('index.html', 
                           prediction_text=result, 
                           res_color=res_color, 
                           risk_score=total_risk)

@app.route('/download_report')
def download_report():
    global last_prediction
    if not last_prediction: return "No Data Available", 400
    
    pdf = FPDF()
    pdf.add_page()
    
    # Professional Header
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(102, 126, 234) 
    pdf.cell(200, 20, txt="Medical Risk Assessment Report", ln=True, align='C')
    pdf.ln(10)
    
    # Patient Data
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(200, 10, txt="Patient Provided Data:", ln=True)
    pdf.set_font("Arial", size=10)
    for k, v in last_prediction['inputs'].items():
        val = v if v.strip() != '' else "0"
        pdf.cell(200, 8, txt=f"- {k}: {val}", ln=True)
    
    pdf.ln(10)
    
    # Final AI Results
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=f"Status: {last_prediction['result']}", ln=True)
    pdf.cell(200, 10, txt=f"Probability Score: {last_prediction['score']}%", ln=True)
    
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, txt="Disclaimer: This assessment is generated by an AI model (Random Forest) for educational purposes. Please consult a registered medical practitioner for clinical diagnosis.")

    output = io.BytesIO()
    pdf_out = pdf.output(dest='S').encode('latin-1')
    output.write(pdf_out)
    output.seek(0)
    
    return send_file(output, 
                     download_name="Medical_Assessment_Report.pdf", 
                     as_attachment=True, 
                     mimetype='application/pdf')

if __name__ == "__main__":
    app.run(debug=True)